# Generated by Django 4.1.3 on 2023-05-16 23:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasktrack_api", "0002_group_list_priority_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="lista",
            new_name="list",
        ),
    ]
