# Generated by Django 4.1.3 on 2023-05-17 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasktrack_api", "0004_alter_task_group_alter_task_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="user",
        ),
        migrations.AddField(
            model_name="group",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
