# Generated by Django 4.1.3 on 2023-05-18 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasktrack_api", "0005_remove_group_user_group_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasktrack_api.priority",
            ),
        ),
    ]
