# Generated by Django 4.1.3 on 2023-05-25 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasktrack_api", "0006_alter_task_description_alter_task_due_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="users",
        ),
        migrations.AddField(
            model_name="task",
            name="users",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
