# Generated by Django 4.1.3 on 2023-05-25 05:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasktrack_api", "0007_remove_task_users_task_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="users",
            new_name="user",
        ),
    ]
