# Generated by Django 4.1.3 on 2023-05-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasktrack_api", "0008_rename_users_task_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="college",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
